// Top 100 most popular research peptides, alphabetically sorted.
// "Other" is always appended last so users can enter a custom value.
export const PEPTIDES: readonly string[] = [
  "5-Amino-1MQ",
  "AOD-9604",
  "Adipotide",
  "Argireline",
  "BPC-157",
  "BPC-157 Arginate",
  "Bremelanotide (PT-141)",
  "CJC-1295",
  "CJC-1295 DAC",
  "CJC-1295 no DAC",
  "Cagrilintide",
  "Cerebrolysin",
  "DSIP",
  "Dapiglutide",
  "Dihexa",
  "Epitalon (Epithalon)",
  "FOXO4-DRI",
  "FST-344 (Follistatin 344)",
  "Fragment 176-191 (HGH Frag)",
  "GHK-Cu",
  "GHRP-2",
  "GHRP-6",
  "GLP-1 (Liraglutide)",
  "Glow Blend (GHK-Cu / BPC / TB)",
  "Gonadorelin",
  "HCG",
  "Hexarelin",
  "Humanin",
  "IGF-1 DES",
  "IGF-1 LR3",
  "Ipamorelin",
  "KPV",
  "Kisspeptin-10",
  "LL-37",
  "Larazotide",
  "MGF (Mechano Growth Factor)",
  "MK-677 (Ibutamoren)",
  "MOTS-C",
  "Melanotan I",
  "Melanotan II",
  "Mod GRF 1-29",
  "NAD+",
  "Oxytocin",
  "P21",
  "PE-22-28",
  "PEG-MGF",
  "PNC-27",
  "PT-141 (Bremelanotide)",
  "Pinealon",
  "Pinealon-2",
  "Pralmorelin (GHRP-2)",
  "Prostamax",
  "Retatrutide",
  "SLU-PP-332",
  "SNAP-8",
  "SS-31 (Elamipretide)",
  "Selank",
  "Semaglutide",
  "Semax",
  "Sermorelin",
  "Snap-29",
  "TB-4 Frag (Ac-SDKP)",
  "TB-500",
  "Tesamorelin",
  "Tesofensine",
  "Thymalin",
  "Thymogen",
  "Thymosin Alpha-1",
  "Thymosin Beta-4",
  "Thyrotropin Releasing Hormone (TRH)",
  "Tirzepatide",
  "VIP (Vasoactive Intestinal Peptide)",
  "Vialox",
  "Adamax",
  "Bacteriostatic Water",
  "Bombesin",
  "C-JC Blend",
  "Cortagen",
  "Cortexin",
  "Crila",
  "DIM",
  "Endorphin (Beta)",
  "Enkephalin",
  "GDF-8 Inhibitor",
  "GDF-11",
  "GHK",
  "Glutathione",
  "Hexapeptide-12",
  "IGF-2",
  "Kallikrein",
  "LGD-4033 Peptide Stack",
  "Lipotropin",
  "MENT",
  "Matrixyl",
  "N-Acetyl Semax",
  "N-Acetyl Selank",
  "Octreotide",
  "Oxiracetam",
  "PEG-IGF",
  "Palmitoyl Pentapeptide-4",
  "Pentadecapeptide BPC",
  "Tetracosactide",
  "Triptorelin",
  "Other",
].slice().sort((a, b) => (a === "Other" ? 1 : b === "Other" ? -1 : a.localeCompare(b)));
