project_id = "oevucjnvgwywitvtsdga"

[functions.create-magic-link]
verify_jwt = false

[functions.get-patient-protocol]
verify_jwt = false

[functions.parse-protocol]
verify_jwt = false

[functions.parse-receipt]
verify_jwt = false
