import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const COMPOUNDS = ["BPC-157", "TB-500", "Ipamorelin", "CJC-1295", "Selank", "Semax", "PT-141", "Other"];
const FREQUENCIES = ["Once Daily", "Twice Daily", "Every Other Day", "Weekly", "Custom"];
const ROUTES = ["Subcutaneous", "Intranasal", "Oral", "Topical"];
const UNITS = ["mcg", "mg", "IU"];

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { text } = await req.json();
    if (!text || typeof text !== "string" || text.trim().length < 5) {
      return new Response(JSON.stringify({ error: "Empty or too-short protocol text" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (text.length > 8000) {
      return new Response(JSON.stringify({ error: "Protocol text too long (max 8000 chars)" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const systemPrompt = `You are a clinical protocol parser. Extract structured peptide protocol fields from free text generated by another AI tool. Match values to the provided enums when possible. If a field cannot be confidently determined, return null for that field. Never invent values.`;

    const body = {
      model: "google/gemini-3-flash-preview",
      messages: [
        { role: "system", content: systemPrompt },
        {
          role: "user",
          content: `Parse this peptide protocol. Allowed compounds: ${COMPOUNDS.join(", ")}. If the compound is named but not in the list, use "Other" and put the actual name in notes. Allowed frequencies: ${FREQUENCIES.join(", ")}. Allowed routes: ${ROUTES.join(", ")}. Allowed dose units: ${UNITS.join(", ")}.\n\nProtocol text:\n"""${text}"""`,
        },
      ],
      tools: [
        {
          type: "function",
          function: {
            name: "extract_protocol",
            description: "Return the parsed protocol fields.",
            parameters: {
              type: "object",
              properties: {
                compound: { type: ["string", "null"], enum: [...COMPOUNDS, null] },
                dose: { type: ["number", "null"] },
                dose_unit: { type: ["string", "null"], enum: [...UNITS, null] },
                frequency: { type: ["string", "null"], enum: [...FREQUENCIES, null] },
                route: { type: ["string", "null"], enum: [...ROUTES, null] },
                duration_days: { type: ["integer", "null"] },
                ongoing: { type: "boolean" },
                notes: { type: ["string", "null"] },
              },
              required: ["compound", "dose", "dose_unit", "frequency", "route", "duration_days", "ongoing", "notes"],
              additionalProperties: false,
            },
          },
        },
      ],
      tool_choice: { type: "function", function: { name: "extract_protocol" } },
    };

    const r = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (r.status === 429) {
      return new Response(JSON.stringify({ error: "Rate limit exceeded, try again shortly." }), {
        status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (r.status === 402) {
      return new Response(JSON.stringify({ error: "AI credits exhausted. Add funds to continue." }), {
        status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (!r.ok) {
      const t = await r.text();
      console.error("AI gateway error", r.status, t);
      return new Response(JSON.stringify({ error: "AI parsing failed" }), {
        status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const json = await r.json();
    const call = json.choices?.[0]?.message?.tool_calls?.[0];
    if (!call?.function?.arguments) {
      return new Response(JSON.stringify({ error: "AI returned no structured output" }), {
        status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const parsed = JSON.parse(call.function.arguments);
    return new Response(JSON.stringify({ parsed }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("parse-protocol error", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
