/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as DashboardVialsRouteImport } from './routes/dashboard/vials'
import { Route as DashboardTodayRouteImport } from './routes/dashboard/today'
import { Route as DashboardStackFeedRouteImport } from './routes/dashboard/stack-feed'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardResearchLogsRouteImport } from './routes/dashboard/research-logs'
import { Route as DashboardProtocolsRouteImport } from './routes/dashboard/protocols'
import { Route as DashboardPatientsRouteImport } from './routes/dashboard/patients'
import { Route as DashboardMyVialsRouteImport } from './routes/dashboard/my-vials'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardCalculatorRouteImport } from './routes/dashboard/calculator'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVialsRoute = DashboardVialsRouteImport.update({
  id: '/vials',
  path: '/vials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTodayRoute = DashboardTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStackFeedRoute = DashboardStackFeedRouteImport.update({
  id: '/stack-feed',
  path: '/stack-feed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResearchLogsRoute = DashboardResearchLogsRouteImport.update({
  id: '/research-logs',
  path: '/research-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProtocolsRoute = DashboardProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyVialsRoute = DashboardMyVialsRouteImport.update({
  id: '/my-vials',
  path: '/my-vials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalculatorRoute = DashboardCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-vials': typeof DashboardMyVialsRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/protocols': typeof DashboardProtocolsRoute
  '/dashboard/research-logs': typeof DashboardResearchLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stack-feed': typeof DashboardStackFeedRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/vials': typeof DashboardVialsRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-vials': typeof DashboardMyVialsRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/protocols': typeof DashboardProtocolsRoute
  '/dashboard/research-logs': typeof DashboardResearchLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stack-feed': typeof DashboardStackFeedRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/vials': typeof DashboardVialsRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-vials': typeof DashboardMyVialsRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/protocols': typeof DashboardProtocolsRoute
  '/dashboard/research-logs': typeof DashboardResearchLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stack-feed': typeof DashboardStackFeedRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/vials': typeof DashboardVialsRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/disclaimer'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/calculator'
    | '/dashboard/home'
    | '/dashboard/my-vials'
    | '/dashboard/patients'
    | '/dashboard/protocols'
    | '/dashboard/research-logs'
    | '/dashboard/settings'
    | '/dashboard/stack-feed'
    | '/dashboard/today'
    | '/dashboard/vials'
    | '/p/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/disclaimer'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/calculator'
    | '/dashboard/home'
    | '/dashboard/my-vials'
    | '/dashboard/patients'
    | '/dashboard/protocols'
    | '/dashboard/research-logs'
    | '/dashboard/settings'
    | '/dashboard/stack-feed'
    | '/dashboard/today'
    | '/dashboard/vials'
    | '/p/$token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/disclaimer'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/calculator'
    | '/dashboard/home'
    | '/dashboard/my-vials'
    | '/dashboard/patients'
    | '/dashboard/protocols'
    | '/dashboard/research-logs'
    | '/dashboard/settings'
    | '/dashboard/stack-feed'
    | '/dashboard/today'
    | '/dashboard/vials'
    | '/p/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vials': {
      id: '/dashboard/vials'
      path: '/vials'
      fullPath: '/dashboard/vials'
      preLoaderRoute: typeof DashboardVialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/today': {
      id: '/dashboard/today'
      path: '/today'
      fullPath: '/dashboard/today'
      preLoaderRoute: typeof DashboardTodayRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stack-feed': {
      id: '/dashboard/stack-feed'
      path: '/stack-feed'
      fullPath: '/dashboard/stack-feed'
      preLoaderRoute: typeof DashboardStackFeedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/research-logs': {
      id: '/dashboard/research-logs'
      path: '/research-logs'
      fullPath: '/dashboard/research-logs'
      preLoaderRoute: typeof DashboardResearchLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/protocols': {
      id: '/dashboard/protocols'
      path: '/protocols'
      fullPath: '/dashboard/protocols'
      preLoaderRoute: typeof DashboardProtocolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients': {
      id: '/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-vials': {
      id: '/dashboard/my-vials'
      path: '/my-vials'
      fullPath: '/dashboard/my-vials'
      preLoaderRoute: typeof DashboardMyVialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator': {
      id: '/dashboard/calculator'
      path: '/calculator'
      fullPath: '/dashboard/calculator'
      preLoaderRoute: typeof DashboardCalculatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCalculatorRoute: typeof DashboardCalculatorRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardMyVialsRoute: typeof DashboardMyVialsRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardProtocolsRoute: typeof DashboardProtocolsRoute
  DashboardResearchLogsRoute: typeof DashboardResearchLogsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStackFeedRoute: typeof DashboardStackFeedRoute
  DashboardTodayRoute: typeof DashboardTodayRoute
  DashboardVialsRoute: typeof DashboardVialsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCalculatorRoute: DashboardCalculatorRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardMyVialsRoute: DashboardMyVialsRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardProtocolsRoute: DashboardProtocolsRoute,
  DashboardResearchLogsRoute: DashboardResearchLogsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStackFeedRoute: DashboardStackFeedRoute,
  DashboardTodayRoute: DashboardTodayRoute,
  DashboardVialsRoute: DashboardVialsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
